### PR TITLE
Publish slack message to slack channel

### PR DESCRIPTION
**Pull request by benlee0423**

### CODE REVIEW

**Comment by arpita0911patel** [comment]
Hi Ben, As per our talk this morning, please test the negative scenario and also build an additional workflow that causes the run's final Slack notice to be sent. The PR can then be merged.
I appreciate your efforts on this.

**Comment by benlee0423** [comment]
@arpita0911patel 
The maximum depth of chaining workflow is three, and we cannot create a workflow that send slack message for the final image build.
Related document is at https://docs.github.com/en/actions/using-workflows/events-that-trigger-workflows#workflow_run

In our case, deps -> t-route -> ngen -> final, which is already three level depth, and the next workflow after final will not run.
I spent a quite of time to figure out why it did not trigger a new slack workflow.

**Comment by benlee0423** [comment]
@arpita0911patel 
There is one more issue when it is running Actions in the branch other than main.
When there is workflow in chaining,
A -> B -> C -> D,
Even though workflow A runs on slack branch, subsequent workflows B,C,and D runs on main branch, I can't test whole scenario in dev branch.
Anything specifically changing the behavior like this, we should directly change in main branch as an exception.

**Comment by benlee0423** [comment]
Positive and negative cases are tested.
There is small code duplication at the final build workflow, and that is not avoidable.

**Comment by arpita0911patel** [comment]
> 
Hi @benlee0423 , thank you for checking on this. 
That could be another reason we should follow Gitflow and have a develop branch. So flow would be:

- Developers create feature branch e.g slack
- Developers merge code to the develop branch
- All four Pipelines should have main, develop branch in the file.
- Once code is merged in develop branch it will run the Actions and test it.
- Once it’s tested , we can merge those changes to the main branch.

Let me know your thoughts.

**Comment by benlee0423** [comment]
@arpita0911patel 
Sure, that's the best practice I know.
Can you just merge this PR and close this ticket first, and then create a separate ticket for that?
I will also do some research if there is better way as well.

**Review by arpita0911patel — APPROVED** [review]
Approving these changes.

**Pull request merged**
