### PR TITLE
Improve docker pipeline

### PR DESCRIPTION
**Pull request by benlee0423**
Separate Dockerfile into base image builds ( t-route and ngen) and final build using those image.
Base images are published in the following location.
https://hub.docker.com/r/awiciroh/ngen
https://hub.docker.com/r/awiciroh/t-route

### CODE REVIEW

**Review by arpita0911patel — COMMENTED** [review]
Ben, as discussed yesterday with this approach we are creating the code duplication in two separate Docker file - Dockerfile.ngen and Dockerfile.t-route.
We might want to discuss the better way to handle long Dockerfile and effective CI workflows for this. @ZacharyWills let us know your thoughts on this.

**Review by arpita0911patel — COMMENTED** [review]
Ben, as discussed yesterday with this approach we are creating the code duplication in two separate Docker file - Dockerfile.ngen and Dockerfile.t-route.
We might want to discuss the better way to handle long Dockerfile and effective CI workflows for this. @ZacharyWills let us know your thoughts on this.

**Comment by benlee0423** [comment]
@arpita0911patel @ZacharyWills Removed redundant code from Dockerfile. Please take a look.

**Comment by ZacharyWills** [comment]
https://github.com/CIROH-UA/CloudInfra/actions/runs/5202971983/jobs/9404875625

Looks like here you're trying to run an ARM image 
Screenshot 2023-06-08 at 13 55 08

On the x86_64 ubuntu-latest runner:
https://github.com/CIROH-UA/CloudInfra/blob/b89e7b0ccc3655c21a0bd8ab33e54105ffa643af/.github/workflows/docker_image_main_branch.yml#L11

This mismatch is the current actions issue: 
Screenshot 2023-06-08 at 13 57 31

**Review by arpita0911patel — APPROVED** [review]
Docker build on local mac laptop worked fine using below commands:
docker build --platform linux/arm64 --tag awiciroh/ngen-deps:latest -f Dockerfile.ngen-deps .
docker build --platform linux/arm64 --tag awiciroh/t-route:latest -f Dockerfile.t-route .
docker build --platform linux/arm64 --tag awiciroh/ngen:latest -f Dockerfile.ngen .
docker build --platform linux/arm64 --tag awiciroh/ciroh-ngen-image:latest -f Dockerfile .

Since both build and test worked fine merging these changes to the repo.

**Pull request merged**
